### ISSUE TITLE
have a bug 

### ISSUE THREAD

**Issue by loong-chen** [sandro-k/MQTTLensChromeApp#13]
when i download MQTTLens on Chrome Store .Open it have a problem,please look at picture:

![0c l0k 1uvfwlg_2 46c2i](https://user-images.githubusercontent.com/28297245/33935769-0f19c6aa-e038-11e7-8945-bea5f085829a.png)

**Comment by VeryMoonen** [comment]
me too

**Comment by vikram-kadian** [comment]
same here

**Comment by vikram-kadian** [comment]
i have been using this app since past one year never had any issue but today its strangely turned into as described by @loong-chen

**Comment by gilles906** [comment]
Hi

Same for me today

**Comment by servim** [comment]
the same problem, perhaps after the chrome update?

**Comment by riccf** [comment]
Me too so I unistalled and reinstalled and all my connections disappeared ...yikes. I thought it would keep connections.

**Comment by NidhiArien** [comment]
me too..

**Comment by loong-chen** [comment]
I think this is the problem of Google browsers，I use the historical version of Google browsers，
The problem has been solved。@VeryMoonen @vikram-kadian @gilles906 @servim @servim @riccf @NidhiArien
