### ISSUE TITLE
MQTT Lens looks like the page is zoomed in 500%

### ISSUE THREAD

**Issue by SteveRMann** [sandro-k/MQTTLensChromeApp#14]
I don't know what happened, but when I launch MQTTLens, I get this:
https://www.dropbox.com/s/9s7br32vd5fij8p/_mqttlens.jpg?dl=0

The usual browser zoom settings have no effect.

**Comment by vivonk** [comment]
Yes, this is the issue but try to launch it from the chrome extensions page

**Comment by Dirnei** [comment]
Same problem. Launching it from the chrome extensions page doesn't help.

**Comment by jot4p** [comment]
same problem here...

**Comment by glynhudson** [comment]
same problem here. Seemed to happen after Chrome 63 update

![screenshot 2018-01-18 at 02 22 00](https://user-images.githubusercontent.com/758844/35077672-612fe38c-fbf6-11e7-849c-1abf6ebbe3f5.png)

**Comment by voglster** [comment]
Also having this issue

**Comment by RosiersRobin** [comment]
Jep... It's f*cked :(

**Comment by iamsven** [comment]
I am having the same issue

**Comment by MattiasEppler** [comment]
Same problem!

**Comment by LeSuedois** [comment]
hey guys, please check my comment here : 
https://github.com/sandro-k/mqtt-lens/issues/2

welcome to 2018!!

**Comment by melkati** [comment]
Same issue here. Chrome 63.0.3239.132 (Build oficial) (64 bits) Windows 10

**Comment by sandro-k** [comment]
I will look how to fix this. Haven’t got any notifications about this.

**Comment by sandro-k** [comment]
It looks like that we probably can use `shadyDom` in Chrome and simulate the deprecated `/deep/` selector. Trying to make a release soon.

**Comment by sandro-k** [comment]
An update is available in the chrome web store. There are no changes nessecary to MQTTLens. I just made some changes to webcomponent.js to use shadydom rather than native shadow dom. It might be ne

**Comment by Dirnei** [comment]
Looks good to me! Thanks for your work!

**Comment by jjtoard** [comment]
look solved

**Comment by glynhudson** [comment]
Woop woop nice work @sandro-k  :+
