### ISSUE TITLE
MQTT '+' wildcard subscriptions

### ISSUE THREAD

**Issue by mmindenhall** [sandro-k/MQTTLensChromeApp#2]
I haven't been able to get subscriptions to work with the '+' wildcard (matches all topics at the same level in the hierarchy).  The '#' wildcard (matches topics at a level *and* all subtopics) is working fine.  

I ran into a bug with the Apache Camel MQTT component on this as well, where the topic subscription strings were getting URL encoded/decoded, and the '+' was getting converted to a space.  I just wanted to mention this in case it's the same problem.

**Comment by sandro-k** [comment]
Hi mmindenhall,

thanks for your feedback. I quickly checked and `foo/+` works fine, but using multiple level of `+` like `SENSOR/+/TEMP` indeed does not work. I will look into this after updating MQTTLens to Polymer 0.5.5 and successfully publishing to the Google Chrome Store.

**Comment by mmindenhall** [comment]
Thanks!  I was trying with something similar to the following: `BASE/+/data/#`.  The `+` matches all devices, and `/data/#` is the hierarchy of topics that devices are publishing to.

**Comment by sandro-k** [comment]
I expect to push an update on Sunday

**Comment by sandro-k** [comment]
Hi mmindenhall,

it took me a little more effort to get 0.0.4 done. I just pushed Pre-release 0.0.5 18b3a6d752ba6b6346b8f52d999a37d781fc3143 and attached [MQTTLens_0.0.5-SNAPSHOT.zip](https://github.com/sandro-k/MQTTLensChromeApp/releases/download/0.0.5/MQTTLens_0.0.5-SNAPSHOT.zip) that solves the wildcard subscription issue
