### ISSUE TITLE
Can't delete a long server name; trash icon hidden and can't expose it due to length of name

### ISSUE THREAD

**Issue by bubba198** [sandro-k/MQTTLensChromeApp#4]
Hi,

I added too long of a name for the mqtt server and now I can not delete it since it takes up the entire space so that the trash icon is not visible and I can not scroll left and right to see it and click on it in order to delete the server? How do I delete the server from the list? 

Thanks
![mqtt](https://cloud.githubusercontent.com/assets/10265342/15089341/1afc08c0-13b6-11e6-8a56-97faf2a99c7f.png)

**Comment by sandro-k** [comment]
Thanks for reporting this bug, I have to come up with a solution to prevent this from happening. In the mean time you can try to uninstall and reinstall MQTTLens?

**Comment by sandro-k** [comment]
@bubba198 I tried to uninstall and reinstall MQTTLens and for me that worked. I will make an update to MQTTLens to wrap long servernames.

**Comment by sandro-k** [comment]
Changes made in https://github.com/sandro-k/mqtt-lens/commit/aa6feafb95c39e7b6388f17fb6b3a59ed639e11e will now wrap long hostnames and make it possible to delete or rename these connection. The update will be within the next MQTTLens release 0.0.7

**Comment by sandro-k** [comment]
@bubba198 MQTTLens 0.0.8 is now released to the Chrom Store, can you confirm that you are now able to delete connections with long names
