### ISSUE TITLE
User authentication - after the fact

### ISSUE THREAD

**Issue by patrickgardella** [sandro-k/MQTTLensChromeApp#5]
I have been testing user authentication on mosquitto primarily using MQTTLens. I found that if I have created the connection, then saved it, and then try to add a username and password, it fails.  But if I recreate the connection with the username and password it works.  

I think this is because modifying the existing connection does not save the username and password. When I reopen MQTTLens, they aren't saved.

I am using MQTTLens 0.0.5 on Chrome 52.0.2743.24 beta (64-bit) on a Mac.

Patrick+

**Comment by sandro-k** [comment]
Thank you for reporting this. It is probably a bug. If you can provide a PR that would be awesome.

**Comment by patrickgardella** [comment]
Interestingly, when I compile it locally, it worked perfectly. I wonder if there was a bug in one of the bower or npm modules that is now fixed, and the version I have compiled resolves that.

I will send a PR for some changes to the main README though that I had to make to get it to compile.

**Comment by sandro-k** [comment]
I check :) It was my fault - I forgot to release the last changes I made. I am creating a release now.

**Comment by sandro-k** [comment]
@patrickgardella I made a new release here and in the Chrome Store, please check if everything is working.

**Comment by patrickgardella** [comment]
Yep!  That did it.  Thank you.
