### ISSUE TITLE
Trim input fields

### ISSUE THREAD

**Issue by Logout22** [sandro-k/MQTTLensChromeApp#7]
If the host name starts or ends with a space, the client will not work. Please trim the input fields before using the values.

**Comment by sandro-k** [comment]
I will make a release tomorrow.

**Comment by Logout22** [comment]
Great, thanks!

**Comment by sandro-k** [comment]
This should be fixed by https://github.com/sandro-k/mqtt-connection-ui/commit/86835d486855e70d4f9990207d2212ced23d4054

**Comment by sandro-k** [comment]
Version 0.0.9 should now be available in the Chrome Store.
