### ISSUE TITLE
Encoding error at message details

### ISSUE THREAD

**Issue by mkrei** [sandro-k/MQTTLensChromeApp#9]
When viewing the message details dialog, the close button is shown as something like Ã--, which is a little confusing at first.
![Screenshot](https://cloud.githubusercontent.com/assets/20699511/17206904/4f7e14ca-54b2-11e6-94bb-656cdfacbbde.png)

**Comment by sandro-k** [comment]
Let me check that.

**Comment by sandro-k** [comment]
I just released a new version 0.0.13, that should soon be available in the Chrome Webstore.

**Comment by mkrei** [comment]
Took me some time, but I just verified the fix. Looks perfectly fine now. Thanks
